<?php

/**
 * BaseRegistro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $serial
 * @property integer $sid
 * @property timestamp $fecha
 * @property string $ip
 * @property string $uid
 * @property string $usuario
 * @property string $email
 * @property string $apellido
 * @property string $nombre
 * @property integer $edad
 * @property string $sexo
 * @property string $localidad
 * @property string $provincia
 * @property string $pais
 * @property string $empresa
 * @property string $sitio
 * @property boolean $asistencia
 * @property boolean $taller_android
 * @property boolean $taller_moodle
 * @property boolean $install_fest
 * @property boolean $certificado
 * 
 * @method integer   getId()             Returns the current record's "id" value
 * @method integer   getSerial()         Returns the current record's "serial" value
 * @method integer   getSid()            Returns the current record's "sid" value
 * @method timestamp getFecha()          Returns the current record's "fecha" value
 * @method string    getIp()             Returns the current record's "ip" value
 * @method string    getUid()            Returns the current record's "uid" value
 * @method string    getUsuario()        Returns the current record's "usuario" value
 * @method string    getEmail()          Returns the current record's "email" value
 * @method string    getApellido()       Returns the current record's "apellido" value
 * @method string    getNombre()         Returns the current record's "nombre" value
 * @method integer   getEdad()           Returns the current record's "edad" value
 * @method string    getSexo()           Returns the current record's "sexo" value
 * @method string    getLocalidad()      Returns the current record's "localidad" value
 * @method string    getProvincia()      Returns the current record's "provincia" value
 * @method string    getPais()           Returns the current record's "pais" value
 * @method string    getEmpresa()        Returns the current record's "empresa" value
 * @method string    getSitio()          Returns the current record's "sitio" value
 * @method boolean   getAsistencia()     Returns the current record's "asistencia" value
 * @method boolean   getTallerAndroid()  Returns the current record's "taller_android" value
 * @method boolean   getTallerMoodle()   Returns the current record's "taller_moodle" value
 * @method boolean   getInstallFest()    Returns the current record's "install_fest" value
 * @method boolean   getCertificado()    Returns the current record's "certificado" value
 * @method Registro  setId()             Sets the current record's "id" value
 * @method Registro  setSerial()         Sets the current record's "serial" value
 * @method Registro  setSid()            Sets the current record's "sid" value
 * @method Registro  setFecha()          Sets the current record's "fecha" value
 * @method Registro  setIp()             Sets the current record's "ip" value
 * @method Registro  setUid()            Sets the current record's "uid" value
 * @method Registro  setUsuario()        Sets the current record's "usuario" value
 * @method Registro  setEmail()          Sets the current record's "email" value
 * @method Registro  setApellido()       Sets the current record's "apellido" value
 * @method Registro  setNombre()         Sets the current record's "nombre" value
 * @method Registro  setEdad()           Sets the current record's "edad" value
 * @method Registro  setSexo()           Sets the current record's "sexo" value
 * @method Registro  setLocalidad()      Sets the current record's "localidad" value
 * @method Registro  setProvincia()      Sets the current record's "provincia" value
 * @method Registro  setPais()           Sets the current record's "pais" value
 * @method Registro  setEmpresa()        Sets the current record's "empresa" value
 * @method Registro  setSitio()          Sets the current record's "sitio" value
 * @method Registro  setAsistencia()     Sets the current record's "asistencia" value
 * @method Registro  setTallerAndroid()  Sets the current record's "taller_android" value
 * @method Registro  setTallerMoodle()   Sets the current record's "taller_moodle" value
 * @method Registro  setInstallFest()    Sets the current record's "install_fest" value
 * @method Registro  setCertificado()    Sets the current record's "certificado" value
 * 
 * @package    acreditacion
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registro');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('serial', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sid', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ip', 'string', 16, array(
             'type' => 'string',
             'length' => 16,
             ));
        $this->hasColumn('uid', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('usuario', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('email', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('apellido', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('nombre', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('edad', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sexo', 'string', 1, array(
             'type' => 'string',
             'length' => 1,
             ));
        $this->hasColumn('localidad', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('provincia', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('pais', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('empresa', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('sitio', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('asistencia', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('taller_android', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('taller_moodle', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('install_fest', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('certificado', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}