<?php

/**
 * RegistroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Registro');
    }
    
    /**
     * hace un truncate table
     */
    public static function truncate() {
      $conn = Doctrine_Core::getConnectionByTableName('Registro');
      $conn->exec('truncate table ' . self::getInstance()->getTableName());
      
    }
}